services:
  - type: web
    name: productos
    env: docker
    plan: free
    repo: https://github.com/JssDevWeb/producrender.git
    branch: main
    rootDir: .
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true